description: >
  Build the tex file into one pdf. The output (log, pdf, ...) is available as artifact.

parameters:
  file:
    type: string
    default: "main.tex"
    description: "The main .tex file to compile."

steps:
  - run:
      name: Build .tex file into .pdf
      shell: /bin/bash
      command: |
        mkdir -p /tmp/tex
        pdflatex -output-directory /tmp/tex <<parameters.file>>
  - store_artifacts:
      path: /tmp/tex
